name: "Issue Triage"
description: "Automatically add labels on newly opened issues"
inputs:
  github_token:
    description: "GitHub access token"
    required: true
    default: ${{ github.token }}
  projects_token:
    description: "Projects Access Token"
    required: false
    default: ""
  project_board:
    description: "Project Board URL"
    required: false
    default: ""
runs:
  using: node16
  main: "build/index.js"
