name: Release to NPM
on:
  push:
    branches:
    - main

jobs:
  release-npm:
    name: Release to NPM
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Codebase
      uses: actions/checkout@v2
    - name: Extract Branch Name
      id: extract_branch
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
    - name: Commit Type
      id: commit_type
      run: |
        branch="##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        echo "##[set-output name=variant;]$(echo "$branch" | awk -F/ '{print $1 FS $2 FS}')"
    - name: Version Bump
      id: bump
      run: |
        echo ${{ steps.commit_type.outputs.variant }}
