name: Release to NPM
on:
  pull_request:
    opened

jobs:
  release-npm:
    name: Release to NPM
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Codebase
      uses: actions/checkout@v2
    - name: Install Bump
      run: npm install -g @jsdevtools/version-bump-prompt
    - name: Extract Branch Name
      id: extract_branch
      shell: bash
      run: echo "{branch}=${GITHUB_REF#refs/heads/}" >> $GITHUB_STATE
    - name: Commit Type
      id: commit_type
      run: |
        branch=${{ steps.extract_branch.outputs.branch }}
        variant="${branch%%/*}"
        echo "{variant}=${variant}" >> $GITHUB_STATE
    - name: Version Bump
      id: bump
      run: |
        case "$variant" in
          "major") bump major
          ;;
          "minor") bump minor
          ;;
          "patch") bump patch
          ;;
        esac
