name: Triage
on:
  issues: # For auto-triage of issues.
    types: [opened, reopened]
  pull_request_target: # For triaging PRs into project boards.
    types: [opened,converted_to_draft,ready_for_review]

jobs:
  issue-triage:
    name: Apply some labels on newly opened issues
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v3

     - name: Setup Node
       uses: actions/setup-node@v3
       with:
          node-version: lts/*

     - name: Build Action
       run: |
          yarn && yarn build
       working-directory: ./.github/actions/triage/

     - name: Run action
       uses: ./.github/actions/triage/
       with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        projects_token: ${{ secrets.TRIAGE_PROJECTS_TOKEN }}
        project_board: https://github.com/users/cameronaziz/projects/10/
